### ISSUE TITLE
如何增加一个新的博客页面呢？

### ISSUE THREAD

**Issue by hxcGit** [ShnHz/say-my-life#37]

**Comment by hxcGit** [comment]
您好， 发现了您的个人博客项目`say-my-life`,非常惊喜它的样式，希望也能制作一个自己的博客。想请教一下，应该如何添加一个blog界面呢？
希望的目录结构如下
<img width="286" alt="image" src="https://user-images.githubusercontent.com/60642406/158043608-f2a22b48-256f-4a5f-bbf1-212dfb27027e.png">

现在该页面已经能访问，但是没有出现在首页条目中，查看代码发现应该是通过blog.json文件进行检索的，而blog.json似乎是通过express来进行更新的，由于没有学习过vue和express相关内容，想请教一下应该如何实现首先增加一个新的blog条目呢？

**Comment by ShnHz** [comment]
blog.json里的数据是我手动加的
